appName: green
namespace: skills
replicaCount: 2
image:
  repository: 637423279607.dkr.ecr.ap-northeast-2.amazonaws.com/skills-green-repo
tag: v1.0.1
service:
  type: ClusterIP
ingress:
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
